### PR TITLE
fix: Ignore IllegalDataAddress in the discovery phase

### PR DESCRIPTION
**Pull request by jacobsvante**
Address 0 for my Fronius GEN24 inverter returned IllegalDataAddress. This fixed the issue for me.

### CODE REVIEW

**Comment by jacobsvante** [comment]
Also - thanks for this great library! I especially love `read_model` and all the auto-generated documentation!

**Comment by bikeshedder** [comment]
Thanks a lot. It really is just a workaround.

**Comment by bikeshedder** [comment]
I refactored that code a bit by moving the logic into the `read_fixed_size` function and changing the match into a `Err(e) if ...` expression. I think a `io::Result<Option<T>>` makes sense for the `read_fixed_size` function anyways if devices are free to reply with that kind of error. See 420d386115d1b1d1d2099c9189dd32dbfce19537

I just released `sunspec 0.3.1` to crates.io including your fix. **Thanks a lot!**

📦 https://crates.io/crates/sunspec/0.3.1

**Comment by jacobsvante** [comment]
Great, thanks! 😃

**Pull request merged**
